#!/usr/bin/env bash
set -euo pipefail

# Feature: container-deployment, Property 5: No sudo in remote podman commands
# Validates: Requirements 5.4
#
# Property: For any SSH command string generated by deploy.sh that contains
# `podman`, that command string should not contain `sudo`.
#
# Strategy:
# Part 1: Static scan of deploy.sh and setup-secrets.sh for `sudo podman`.
# Part 2: Dynamic test — source deploy.sh, call functions that issue SSH
#   commands containing `podman` (check_secrets, ensure_dirs), capture the
#   remote command strings via a mock ssh, and verify none contain `sudo`.
#   For each iteration, randomize project names and secret subsets.
# Part 3: Exhaustive source scan — extract all quoted strings passed to ssh
#   in deploy.sh that contain `podman` and verify none contain `sudo`.
# Minimum 100 iterations.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

ITERATIONS=100
PASS_COUNT=0
FAIL_COUNT=0

# Temp directories and files
MOCK_BIN=""
SSH_LOG=""
STDERR_FILE=""

cleanup() {
    rm -rf "$MOCK_BIN" "$SSH_LOG" "$STDERR_FILE" /tmp/pbt-nosudo5-*
}
trap cleanup EXIT

MOCK_BIN=$(mktemp -d /tmp/pbt-nosudo5-mockbin-XXXXXX)
SSH_LOG=$(mktemp /tmp/pbt-nosudo5-sshlog-XXXXXX)
STDERR_FILE=$(mktemp /tmp/pbt-nosudo5-stderr-XXXXXX)

echo "=== Property Test: No sudo in remote podman commands ==="
echo ""

# ---------------------------------------------------------------------------
# Part 1: Static scan of script files for `sudo podman`
# ---------------------------------------------------------------------------
echo "--- Part 1: Static scan for 'sudo podman' ---"

static_fail=false

for script in "$REPO_ROOT/scripts/deploy.sh" "$REPO_ROOT/scripts/setup-secrets.sh"; do
    if [[ ! -f "$script" ]]; then
        echo "SKIP: $script not found"
        continue
    fi
    if grep -nE '\bsudo\s+podman\b' "$script" 2>/dev/null; then
        echo "FAIL: found 'sudo podman' in $(basename "$script")"
        static_fail=true
    else
        echo "OK: no 'sudo podman' in $(basename "$script")"
    fi
done

if [[ "$static_fail" == true ]]; then
    echo ""
    echo "PROPERTY TEST FAILED (static scan)"
    exit 1
fi

# ---------------------------------------------------------------------------
# Part 2: Extract all SSH command strings from deploy.sh source that contain
# `podman` and verify none contain `sudo`. This is a source-level property
# check across all possible code paths.
# ---------------------------------------------------------------------------
echo ""
echo "--- Part 2: Source-level SSH command extraction ---"

# Extract all strings passed as the last argument to ssh calls in deploy.sh.
# These are the remote commands. Look for patterns like:
#   ssh ... "...podman..."
#   ssh ... '...podman...'
# Also check for heredoc or variable-based patterns.
source_fail=false

# Grep for any line containing both ssh and podman — these are the SSH commands
# that run podman remotely. Check each for sudo.
while IFS= read -r line; do
    # Skip comment lines
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    # This line invokes ssh with a podman command — check for sudo
    if [[ "$line" == *sudo* ]]; then
        echo "FAIL: SSH+podman line contains sudo:"
        echo "  $line"
        source_fail=true
    fi
done < <(grep -E '\bssh\b.*\bpodman\b' "$REPO_ROOT/scripts/deploy.sh" 2>/dev/null || true)

# Also check setup-secrets.sh
while IFS= read -r line; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    if [[ "$line" == *sudo* ]]; then
        echo "FAIL: SSH+podman line contains sudo in setup-secrets.sh:"
        echo "  $line"
        source_fail=true
    fi
done < <(grep -E '\bssh\b.*\bpodman\b' "$REPO_ROOT/scripts/setup-secrets.sh" 2>/dev/null || true)

if [[ "$source_fail" == true ]]; then
    echo "PROPERTY TEST FAILED (source-level scan)"
    exit 1
fi

echo "OK: all SSH+podman lines are sudo-free in source"

# ---------------------------------------------------------------------------
# Part 3: Dynamic test — call implemented functions with random inputs
# ---------------------------------------------------------------------------
echo ""
echo "--- Part 3: Dynamic test ($ITERATIONS iterations) ---"
echo ""

# Create mock ssh that logs the remote command (last arg)
cat > "$MOCK_BIN/ssh" << 'MOCK_SSH_EOF'
#!/usr/bin/env bash
# Mock ssh: logs the remote command (last argument) to SSH_LOG_FILE.
cmd="${@: -1}"
echo "$cmd" >> "$SSH_LOG_FILE"

# Provide minimal mock responses
if [[ "$cmd" == *"podman secret ls"* ]]; then
    if [[ -f "$MOCK_SECRETS_FILE" ]]; then
        cat "$MOCK_SECRETS_FILE"
    fi
    exit 0
fi

# Default: succeed silently
exit 0
MOCK_SSH_EOF
chmod +x "$MOCK_BIN/ssh"

# Source deploy.sh to get functions and REQUIRED_SECRETS
source "$REPO_ROOT/scripts/deploy.sh"

# Character set for random generation
ALPHANUM="abcdefghijklmnopqrstuvwxyz0123456789"

rand_string() {
    local len="$1"
    local result=""
    local charset_len=${#ALPHANUM}
    for (( j=0; j<len; j++ )); do
        result+="${ALPHANUM:$(( RANDOM % charset_len )):1}"
    done
    echo -n "$result"
}

# Check SSH log for sudo+podman violations
check_log_for_sudo_podman() {
    if [[ ! -s "$SSH_LOG" ]]; then
        return 0
    fi
    while IFS= read -r line; do
        if [[ "$line" == *podman* ]] && [[ "$line" == *sudo* ]]; then
            echo "  VIOLATION: $line"
            return 1
        fi
    done < "$SSH_LOG"
    return 0
}

# Override PATH so our mock ssh is found first
export PATH="$MOCK_BIN:$PATH"

# Set SSH variables that functions expect
export SSH_TARGET="mock@localhost"
export SSH_OPTS=""
export SSH_LOG_FILE="$SSH_LOG"

# Create a mock secrets file
MOCK_SECRETS_FILE=$(mktemp /tmp/pbt-nosudo5-secrets-XXXXXX)
export MOCK_SECRETS_FILE

for (( i=1; i<=ITERATIONS; i++ )); do
    # Clear SSH log each iteration
    > "$SSH_LOG"
    > "$STDERR_FILE"

    # Generate random project name (3-12 chars)
    proj_len=$(( (RANDOM % 10) + 3 ))
    project=$(rand_string "$proj_len")

    # Generate random set of secrets to be "present"
    > "$MOCK_SECRETS_FILE"
    for secret in "${REQUIRED_SECRETS[@]}"; do
        if (( RANDOM % 2 == 0 )); then
            echo "$secret" >> "$MOCK_SECRETS_FILE"
        fi
    done

    # --- Call check_secrets (issues podman secret ls via SSH) ---
    check_secrets > /dev/null 2>"$STDERR_FILE" || true

    if ! check_log_for_sudo_podman; then
        FAIL_COUNT=$((FAIL_COUNT + 1))
        echo "FAIL iteration $i (check_secrets): sudo+podman found in SSH commands"
        echo "  Project: $project"
        sed 's/^/    /' "$SSH_LOG"
        continue
    fi

    # Clear log for next function
    > "$SSH_LOG"

    # --- Call ensure_dirs (issues mkdir via SSH, no podman but verify anyway) ---
    ensure_dirs "$project" > /dev/null 2>"$STDERR_FILE" || true

    if ! check_log_for_sudo_podman; then
        FAIL_COUNT=$((FAIL_COUNT + 1))
        echo "FAIL iteration $i (ensure_dirs): sudo+podman found in SSH commands"
        echo "  Project: $project"
        sed 's/^/    /' "$SSH_LOG"
        continue
    fi

    PASS_COUNT=$((PASS_COUNT + 1))
done

rm -f "$MOCK_SECRETS_FILE"

echo ""
echo "=== Results ==="
echo "Iterations: $ITERATIONS"
echo "Passed:     $PASS_COUNT"
echo "Failed:     $FAIL_COUNT"

if [[ $FAIL_COUNT -gt 0 ]]; then
    echo ""
    echo "PROPERTY TEST FAILED"
    exit 1
fi

echo ""
echo "PROPERTY TEST PASSED"
exit 0
