#!/usr/bin/env bash
set -euo pipefail

# Feature: container-deployment, Property 6: Secret injection covers all required config
# Validates: Requirements 2.2, 5.2
#
# Property: For any set of required configuration keys, the podman run command
# generated by start_container() should contain a --secret <key>,type=env flag
# for each required key in REQUIRED_SECRETS.
#
# Strategy: Create a mock ssh script that logs every command it receives.
# Source deploy.sh to get start_container, ensure_dirs, and REQUIRED_SECRETS.
# For each iteration:
#   1. Generate a random project name
#   2. Generate random repo URLs (0-3)
#   3. Randomly choose mode (cli/server) and port
#   4. Call start_container with these args
#   5. Find the logged podman run command
#   6. Verify it contains --secret <key>,type=env for EVERY entry in REQUIRED_SECRETS

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Source deploy.sh to get start_container, ensure_dirs, REQUIRED_SECRETS
source "$REPO_ROOT/scripts/deploy.sh"

ITERATIONS=100
PASS_COUNT=0
FAIL_COUNT=0

# Temp directories and files
MOCK_BIN=""
SSH_LOG=""
STDERR_FILE=""

cleanup() {
    rm -rf "$MOCK_BIN" "$SSH_LOG" "$STDERR_FILE"
}
trap cleanup EXIT

MOCK_BIN=$(mktemp -d /tmp/pbt-secretinj-mockbin-XXXXXX)
SSH_LOG=$(mktemp /tmp/pbt-secretinj-sshlog-XXXXXX)
STDERR_FILE=$(mktemp /tmp/pbt-secretinj-stderr-XXXXXX)

# ---------------------------------------------------------------------------
# Create mock ssh script
# ---------------------------------------------------------------------------
cat > "$MOCK_BIN/ssh" << 'MOCK_SSH_EOF'
#!/usr/bin/env bash
# Mock ssh that logs every command and provides minimal responses.
# Uses SSH_LOG_FILE env var for the log file.

cmd="${@: -1}"
echo "$cmd" >> "$SSH_LOG_FILE"

# For podman ps checks: return empty (no existing container)
if [[ "$cmd" == *"podman ps"* ]]; then
    echo ""
    exit 0
fi

# For mkdir -p: succeed silently
if [[ "$cmd" == *"mkdir -p"* ]]; then
    exit 0
fi

# For podman run: succeed and return a fake container ID
if [[ "$cmd" == *"podman run"* ]]; then
    echo "abc123def456"
    exit 0
fi

# Default: succeed silently
exit 0
MOCK_SSH_EOF
chmod +x "$MOCK_BIN/ssh"

# ---------------------------------------------------------------------------
# Character sets for random generation
# ---------------------------------------------------------------------------
ALPHANUM="abcdefghijklmnopqrstuvwxyz0123456789"

rand_string() {
    local len="$1"
    local result=""
    local charset_len=${#ALPHANUM}
    for (( j=0; j<len; j++ )); do
        result+="${ALPHANUM:$(( RANDOM % charset_len )):1}"
    done
    echo -n "$result"
}

rand_repo_url() {
    local name
    name=$(rand_string $(( (RANDOM % 8) + 3 )))
    echo "https://github.com/user/${name}.git"
}

# ---------------------------------------------------------------------------
# Test loop
# ---------------------------------------------------------------------------

echo "=== Property Test: Secret injection covers all required config ==="
echo "Running $ITERATIONS iterations..."
echo ""

# Override PATH so our mock ssh is found first
export PATH="$MOCK_BIN:$PATH"

# Set SSH variables that start_container expects
export SSH_TARGET="mock@localhost"
export SSH_OPTS=""
export SSH_LOG_FILE="$SSH_LOG"

for (( i=1; i<=ITERATIONS; i++ )); do
    # Clear state
    > "$SSH_LOG"
    > "$STDERR_FILE"

    # Generate random project name (3-12 chars)
    proj_len=$(( (RANDOM % 10) + 3 ))
    project=$(rand_string "$proj_len")

    # Generate random repo URLs (0-3)
    num_repos=$(( RANDOM % 4 ))
    repos=()
    for (( r=0; r<num_repos; r++ )); do
        repos+=("$(rand_repo_url)")
    done

    # Randomly choose mode
    if (( RANDOM % 2 == 0 )); then
        mode="cli"
    else
        mode="server"
    fi

    # Random port (1024-65535)
    port=$(( (RANDOM % 64511) + 1024 ))

    # Call start_container
    start_container "$project" "false" "$mode" "$port" "${repos[@]+"${repos[@]}"}" \
        > /dev/null 2>"$STDERR_FILE" || true

    # Find the podman run command in the SSH log
    podman_run_cmd=$(grep "podman run" "$SSH_LOG" 2>/dev/null || true)

    if [[ -z "$podman_run_cmd" ]]; then
        FAIL_COUNT=$((FAIL_COUNT + 1))
        echo "FAIL iteration $i: no 'podman run' command found in SSH log"
        echo "  Project: $project, Mode: $mode, Repos: ${repos[*]:-none}"
        echo "  SSH log contents:"
        sed 's/^/    /' "$SSH_LOG"
        continue
    fi

    # Verify each required secret is injected
    check_failed=false
    for secret in "${REQUIRED_SECRETS[@]}"; do
        if [[ "$podman_run_cmd" != *"--secret ${secret},type=env"* ]]; then
            FAIL_COUNT=$((FAIL_COUNT + 1))
            echo "FAIL iteration $i: missing --secret ${secret},type=env in podman run command"
            echo "  Project: $project, Mode: $mode, Repos: ${repos[*]:-none}"
            echo "  Command: $podman_run_cmd"
            check_failed=true
            break
        fi
    done

    if [[ "$check_failed" == true ]]; then
        continue
    fi

    PASS_COUNT=$((PASS_COUNT + 1))
done

echo ""
echo "=== Results ==="
echo "Iterations: $ITERATIONS"
echo "Passed:     $PASS_COUNT"
echo "Failed:     $FAIL_COUNT"

if [[ $FAIL_COUNT -gt 0 ]]; then
    echo ""
    echo "PROPERTY TEST FAILED"
    exit 1
fi

echo ""
echo "PROPERTY TEST PASSED"
exit 0
